namespace: kubeflow
resources:
- mlflow-mysql-deployment.yaml
- mlflow-mysql-pvc.yaml
- mlflow-mysql-service.yaml
- mlflow-ui-deployment.yaml
- mlflow-ui-rbac.yaml
- mlflow-ui-service.yaml
images:
- name: mysql/mysql-server
  newTag: 5.7.28
  newName: mysql/mysql-server
- name: localhost:32000/mlflow_server
  newTag: latest
  newName: localhost:32000/mlflow_server