apiVersion: v1
kind: Service
metadata:
  name: mlflow-ui
  labels:
    app: mlflow
    component: ui
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      name: ui
      targetPort: 5000
  selector:
    app: mlflow
    component: ui