kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mlflow-ui
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - namespaces
  verbs:
  - "*"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlflow-ui
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mlflow-ui
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: mlflow-ui
subjects:
- kind: ServiceAccount
  name: mlflow-ui
