apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- istio-install.yaml
namespace: kubeflow
images:
- name: docker.io/istio/galley
  newName: docker.io/istio/galley
  newTag: 1.4.3
- name: docker.io/istio/proxyv2
  newName: docker.io/istio/proxyv2
  newTag: 1.4.3
- name: docker.io/istio/mixer
  newName: docker.io/istio/mixer
  newTag: 1.4.3
- name: docker.io/istio/pilot
  newName: docker.io/istio/pilot
  newTag: 1.4.3
- name: docker.io/prom/prometheus
  newName: docker.io/prom/prometheus
  newTag: v2.12.0
- name: docker.io/istio/citadel
  newName: docker.io/istio/citadel
  newTag: 1.4.3
- name: docker.io/istio/sidecar_injector
  newName: docker.io/istio/sidecar_injector
  newTag: 1.4.3